CREATE TABLE TIPO_VEHICULO (
    ID_TIPO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255)
);

CREATE TABLE POLITICA_VEHICULO (
    ID_POLITICA VARCHAR(50) NOT NULL,
    ID_TIPO VARCHAR(50) NOT NULL,
    TARIFA_HORA DECIMAL(10, 2) NOT NULL,
    TIEMPO_MAX_MIN INTEGER NOT NULL,
    RESTRICCIONES VARCHAR(500),
    VIGENTE SMALLINT DEFAULT 1 NOT NULL
);

CREATE TABLE VEHICULO (
    ID_VEHICULO VARCHAR(50) NOT NULL,
    CODIGO VARCHAR(50) NOT NULL,
    ID_TIPO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL -- Ej: 'DISPONIBLE', 'EN_USO', 'MANTENIMIENTO'
);

CREATE TABLE RESERVACION (
    ID_RESERVACION VARCHAR(50) NOT NULL,
    CODIGO_RESERVA VARCHAR(50) NOT NULL,
    ID_VEHICULO VARCHAR(50) NOT NULL,
    ID_USUARIO VARCHAR(255) NOT NULL,
    INICIO TIMESTAMP NOT NULL,
    FIN TIMESTAMP NOT NULL,
    ESTADO VARCHAR(20) NOT NULL, -- Ej: 'ACTIVA', 'COMPLETADA', 'CANCELADA'
    TOTAL_ESTIMADO DECIMAL(10, 2),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
);
