-- Primary Keys
ALTER TABLE TIPO_VEHICULO ADD CONSTRAINT PK_TIPO_VEHICULO PRIMARY KEY (ID_TIPO);
ALTER TABLE POLITICA_VEHICULO ADD CONSTRAINT PK_POLITICA_VEHICULO PRIMARY KEY (ID_POLITICA);
ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO PRIMARY KEY (ID_VEHICULO);
ALTER TABLE RESERVACION ADD CONSTRAINT PK_RESERVACION PRIMARY KEY (ID_RESERVACION);

-- Unique Constraints
ALTER TABLE VEHICULO ADD CONSTRAINT UQ_VEHICULO_CODIGO UNIQUE (CODIGO);
ALTER TABLE RESERVACION ADD CONSTRAINT UQ_RESERVACION_CODIGO UNIQUE (CODIGO_RESERVA);

-- Foreign Keys
ALTER TABLE POLITICA_VEHICULO 
ADD CONSTRAINT FK_POLITICA_TIPO 
FOREIGN KEY (ID_TIPO) REFERENCES TIPO_VEHICULO(ID_TIPO) ON DELETE CASCADE;

ALTER TABLE VEHICULO 
ADD CONSTRAINT FK_VEHICULO_TIPO 
FOREIGN KEY (ID_TIPO) REFERENCES TIPO_VEHICULO(ID_TIPO) ON DELETE RESTRICT;

ALTER TABLE RESERVACION 
ADD CONSTRAINT FK_RESERVACION_VEHICULO 
FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO) ON DELETE RESTRICT;
