-- 004_add_check_constraints.sql
-- Evolution script to enforce domain constraints for UV-Move

-- POLITICA_VEHICULO
ALTER TABLE POLITICA_VEHICULO ADD CONSTRAINT CHK_TARIFA_HORA CHECK (TARIFA_HORA >= 0);
ALTER TABLE POLITICA_VEHICULO ADD CONSTRAINT CHK_TIEMPO_MAX_MIN CHECK (TIEMPO_MAX_MIN > 0);

-- RESERVACION
ALTER TABLE RESERVACION ADD CONSTRAINT CHK_INICIO_FIN CHECK (INICIO < FIN);
